FROM aem-base:latest

ARG CQ_RUNMODE
ARG CQ_PORT
ARG AEM_JMXPORT

ENV CQ_RUNMODE $CQ_RUNMODE
ENV CQ_PORT $CQ_PORT
ENV AEM_JMXPORT $AEM_JMXPORT

ENV CQ_JVM_OPTS="\
-Dcom.sun.management.jmxremote.local.only=true \
-Dcom.sun.management.jmxremote.port=$AEM_JMXPORT \
-Dcom.sun.management.jmxremote.ssl=false \
-Dcom.sun.management.jmxremote.authenticate=false \
-server -XX:MaxPermSize=256M -Xmx1024m -Djava.awt.headless=true"

COPY tools $AEM_DIR/tools

RUN echo sling.run.modes=${CQ_RUNMODE} >> crx-quickstart/conf/sling.properties && \
    tools/startup.sh -exit

# TODO clean shutdown
#RUN crx-quickstart/bin/stop
# ...fails like so:
#Step 7 : RUN crx-quickstart/bin/stop
# ---> Running in d9e757e9013d
#27.02.2017 15:54:07.479 *INFO * [main] Setting sling.home=. (command line)
#27.02.2017 15:54:07.506 *INFO * [main] No Apache Sling running at /127.0.0.1:41658
#Stop command returned 3. Trying to kill the process...
#process 16 not running
#The command '/bin/sh -c crx-quickstart/bin/stop' returned a non-zero code: 4

CMD ["tools/startup.sh","-noexit"]
